config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
      resources :gists, only: :create
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges, only: %i[new create]
  end

  resources :feedback, only: %i[index create]
  resources :badges, only: :index
end

app/models/admin.rb
class Admin < User
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :text, presence: true
  validate :validate_answers_limit, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_answers_limit
    errors.add(:answer, "Max answers for one questions is 4") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :ASC) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :text, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true }
  validates :time, numericality: { only_integer: true, greater_then: 0 }

  scope :easy_level, -> { where(level: 0..1) }
  scope :medium_level, -> { where(level: 2..4) }
  scope :hard_level, -> { where(level: 5..Float::INFINITY) }
  scope :with_category_desc, lambda { |title_category|
                                     joins(:category).where(category: { title: title_category }).order(title: :DESC)
                                   }

  def self.with_category_desc_in_array(title_category)
    with_category_desc(title_category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_qustion

  SUCCESS_RATIO = 85

  def complited?
    current_question.nil? || (created_at + self.test.time) - Time.zone.now <= 0
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answers?(answer_ids)
    save!
  end

  def succeeded?
    correct_percent >= SUCCESS_RATIO
  end

  def correct_percent
    correct_questions.to_f * 100 / test.questions.count
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def get_time
    (created_at + self.test.time) - Time.zone.now
  end

  private

  def before_validation_set_current_qustion
    self.current_question = next_question
  end

  def correct_answers?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      self.current_question = test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :test_author, class_name: 'Test', foreign_key: :author_id
  has_many :gists, dependent: :destroy
  has_many :user_badges
  has_many :badges, through: :user_badges, dependent: :destroy

  EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.freeze

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_FORMAT }

  def complied_tests_on_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all.pluck(:img_name)
    @user_badges = current_user.badges.pluck(:img_name)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  def create
    @test_passage = TestPassage.find(params[:id])
    @new_gist = GistQuestionService.new(@test_passage.current_question).call
    @test_passage.current_question.gists.create!(user_id: current_user.id, url: @new_gist.url)

    if @new_gist.success?
      flash_options = { notice: t('.success', url: @new_gist.url) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def github_url(author, repo)
    link_to 'TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank', rel: 'nofollow noopener'
  end

  def current_year
    Time.now.year
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  TEXT_LENGTH = 25

  def gist_url(gist)
    link_to gist.url, "#{gist.url}", rel: 'noopener nofollow', target: '_blank'
  end

  def gist_question(gist)
    question = gist.question
    link_to question.text.truncate(TEXT_LENGTH), admin_question_path(question)
  end

  def gist_user_email(gist)
    gist.user.email
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} Question"
    else
      "Create New #{question.test.title} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title">TestGuru admin panel</span>

  <div class="nav-admin user">
    Welcome, <b class="nav-admin user-name"><%= current_user.name %></b> |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru | Admin Panel</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "alert alert-success #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="fixed-bottom bg-light text-center text-lg-start">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    Author: Netesanov Andrei
    <%= github_url("AndRBuZ","test-guru") %>
    <a href="https://thinknetica.com/" target="_blank" rel="nofollow noopener">Учебный проект в онлайн-школе THINKNETICA</a>
    <%= current_year %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <ul>
    <li><a><%= link_to 'TestGuru', tests_path %></a></li>
      <% if user_signed_in? %>
        <li style="float:right"><a><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %></a></li>
        <a style="float:right">Welcome, <%= current_user.name %> Guru</a>
      <% end %>

      <% if !user_signed_in? %>
        <li style="float:right"><a><%= link_to 'Registration', new_user_registration_path %></a></li>
        <li style="float:right"><a><%= link_to 'Login', new_user_session_path %></a></li>
      </p>
    <% end %>
  </ul>
</header>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      <% if admin? %>
        <button type="button" class="btn btn-outline-primary">
          <%= link_to 'AdminPanel', admin_tests_path %>
        </button>
      <% end %>
      <button type="button" class="btn btn-outline-primary">
        <%= link_to 'Badges', badges_path %>
      </button>
      <button type="button" class="btn btn-outline-primary">
        <%= link_to 'Feedback', feedback_index_path %>
      </button>
      Welcome, <%= current_user.name %> Guru |
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% else %>
      <%= link_to "Log in", new_user_session_path %> |
      <%= link_to "Sign in", new_user_registration_path %>
    <% end %>
  </span>
</nav>