config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
      resources :gists, only: :create
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges, only: %i[new create]
  end

  resources :feedback, only: %i[index create]
  resources :badges, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :text, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit destroy update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def edit; end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test_id)
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question.id)
    else
      render :edit
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:text)
  end

  def rescue_with_question_not_found
    render plain: 'Question not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} Question"
    else
      "Create New #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<p><%= question_header(@question) %>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :text %>
    <%= form.text_field :text %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.text %></td>
  <td><%= link_to t('Show'), admin_question_path(question) %></td>
  <td><%= link_to t('Edit'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('Delete'), admin_question_path(question),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
  </td>
</td>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

<p><%= link_to 'Back', admin_test_path(@question.test_id) %></p>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

<p><%= link_to 'Back', admin_test_path(@question.test_id) %></p>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p><%= @question.text %></p>

<h2>Answers</h2>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<p><%= link_to 'Back', admin_test_path(@question.test_id) %></p>